docker run -d \
  --name mysql8 \
  -p 3306:3306 \
  -e MYSQL_ROOT_PASSWORD=123456 \
  -e TZ=Asia/Shanghai \
  -v /Users/yuejin/88env/docker/mysql8/data:/var/lib/mysql \
  -v /Users/yuejin/88env/docker/mysql8/conf:/etc/mysql/conf.d \
  mysql:8.0


docker run -d \
  --name nacos \
  -p 8848:8848 \
  -p 9848:9848 \
  -p 9849:9849 \
  -e MODE=standalone \
  -e SPRING_DATASOURCE_PLATFORM=mysql \
  -v /Users/yuejin/88env/docker/nacos/conf/application.properties:/home/nacos/conf/application.properties \
  -v /Users/yuejin/88env/docker/nacos/logs:/home/nacos/logs \
  --add-host=host.docker.internal:host-gateway \
  nacos/nacos-server:v2.5.2





docker run --name redis -p 6379:6379 \
  -v /Users/yuejin/88env/docker/redis/data:/data \
  -v /Users/yuejin/88env/docker/redis/conf/redis.conf:/etc/redis/redis.conf \
  -d redis:latest redis-server /etc/redis/redis.conf 
